title: KYLA SMITH # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  illustration, comics, graphic design, writing
  <br><br>
  aikosmith [at] gmail [dot] com
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158485515-1 # your Google Analytics tracking ID here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here, could put this logo under title and above description
